#components:
#    schemas:
#        APIErrorResult:
#            type: object
#            properties:
#                errorsMessages:
#                    type: array
#                    nullable: true
#                    items:
#                        $ref: '#/components/schemas/Paginator<h03.BlogViewModel>'
#
#        FieldError:
#            type: object
#            properties:
#                field:
#                    type: string
#                    nullable: true
#                    description: Message with error explanation for certain field
#                    example: 'name'
#                message:
#                    type: string
#                    nullable: true
#                    description: What field/property of input model has error
#                    example: 'Invalid name'
#            required:
#                - field
#                - message
#
#
#        Paginator<h03.BlogViewModel>:
#            type: object
#            properties:
#                pagesCount:
#                    type: integer
#                    example: 5
#                page:
#                    type: integer
#                    example: 1
#                pageSize:
#                    type: integer
#                    example: 10
#                totalCount:
#                    type: integer
#                    example: 42
#                items:
#                    type: array
#                    items:
#                        $ref: '#/components/schemas/BlogViewModel'
#            required:
#                - pagesCount
#                - page
#                - pageSize
#                - totalCount
#                - items
#
#
#        BlogViewModel:
#            type: object
#            properties:
#                id:
#                    type: integer
#                    example: 2
#                name:
#                    type: string
#                    example: "Tom Rider"
#                description:
#                    type: string
#                    example: "Experienced professional driver"
#                websiteUrl:
#                    type: string
#                    example: "https://example.com/blog"
#                createdAt:
#                    type: string
#                    format: date-time
#                    example: "2023-03-05T12:00:00Z"
#                isMembership:
#                    type: boolean
#                    example: false
#            required:
#                - id
#                - name
#                - description
#                - websiteUrl
#                - createdAt
#                - isMembership
#        BlogInputModel:
#            type: object
#            properties:
#                name:
#                    type: string
#                    maxLength: 15
#                description:
#                    type: string
#                    maxLength: 500
#                website:
#                    type: string
#                    maxLength: 100
#                    pattern: ^https://([a-zA-Z0-9_-]+\.)+[a-zA-Z0-9_-]+(\/[a-zA-Z0-9_-]+)*\/?
#            required:
#                - name
#                - description
#                - website
#
#
#        PostPaginator:
#            type: object
#            properties:
#                pagesCount:
#                    type: integer
#                    example: 5
#                page:
#                    type: integer
#                    example: 1
#                pageSize:
#                    type: integer
#                    example: 10
#                totalCount:
#                    type: integer
#                    example: 42
#                items:
#                    type: array
#                    items:
#                        $ref: '#/components/schemas/PostViewModel'
#
#
#        PostViewModel:
#            type: object
#            properties:
#                id:
#                    type: integer
#                    example: 1
#                title:
#                    type: string
#                    example: 'title'
#                shortDescription:
#                    type: string
#                    example: 'lalala'
#                content:
#                    type: string
#                    example: 'With some content'
#                blogId:
#                    type: string
#                    example: '1lk3lkc4t23knr43k'
#                blogName:
#                    type: string
#                    example: 'Blog Name'
#                createdAt:
#                    type: string
#                    example: "2025-05-19T17:35:27.374Z"
#            required:
#                - id
#                - title
#                - shortDescription
#                - content
#                - blogId
#                - blogName
#                - createdAt