openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0

tags:
  - name: Blogs
    description: API for Blogs

paths:
  /blogs:
    get: #Get Запрос
      summary: Return Blogs with pagination
      tags: [Blogs]
      parameters:
        - in: query
          name: pageNumber
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
            default: 10
          description: Number of items per page
        - in: query
          name: sortBy
          schema:
            type: string
            enum: [ createdAt, clientName, price, startedAt, finishedAt ]
            default: createdAt
          description: Field to sort by
        - in: query
          name: sortDirection
          schema:
            type: string
            enum: [ asc, desc ]
            default: desc
          description: Sort direction

      responses:
        '200':
          description: List of all blogs
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/PaginatorBlogViewModel"

    post:
      summary: Create a new blog

      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogViewModel'
      responses:
        201:
          description: Successfully

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    BlogViewModel:
      type: object
      properties:
        id:
          type: string
          example: '2'
        name:
          type: string
          example: John Snow
        description:
          type: string
          example: John Snow kill Dany
        websiteUrl:
          type: string
          example: "https://example.com"
        createdAt:
          type: string
          example: "2025-06-05T12:00:00Z"
        isMembership:
          type: boolean
          example: false
      required:
        - id
        - name
        - description
        - websiteUrl
        - createdAt
        - isMembership

    PaginatorBlogViewModel:
      type: object
      properties:
        pagesCount:
          type: integer
          example: 5
        page:
          type: integer
          example: 1
        pageSize:
          type: integer
          example: 10
        totalCount:
          type: integer
          example: 10
        items:
          type: array
          items:
            $ref: '#/components/schemas/BlogViewModel'

    CreatedBlogModel:
      type: object
      properties:
        id:
          type: string
          example: '2'
        name:
          type: string
          example: John Snow
        description:
          type: string
          example: John Snow kill Dany
        websiteUrl:
          type: string
          example: "https://example.com"
        createdAt:
          type: string
          example: "2025-06-05T12:00:00Z"
        isMembership:
          type: boolean
          example: false
      required:
        - id
        - name
        - description
        - websiteUrl
        - createdAt
        - isMembership