paths:
  /api/posts:

    get:
      parameters:
        - name: searchNameTerm
          in: query
          description: 'Search term for blog Name: Name should contains this term in any position'
          required: false
          schema:
            type: string
            default: null
        - name: sortBy
          in: query
          schema:
            type: string
            default: createdAt
        - name: sortDirection
          in: query
          schema:
            type: string
            description: 'Default value: desc'
            default: desc, asc
        - name: pageNumber
          in: query
          description: 'pageNumber is number of portions that should be returned'
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          schema:
            type: integer
            description: 'pageSize is number of portions that should be returned'
            default: 10
      summary: Get a list of all blogs
      tags: [ Posts ]
      responses:
        200:
          description: List of all blogs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Paginator<h03.BlogViewModel>'